<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>5b60a1d6-3735-4196-952a-0a0c78d89d60</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Sorry, we do not have much information about you. Please enter your Name." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
